version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile      
    ports:
      - 8080:80
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8081:3000
    restart: always
